### ISSUE TITLE
Crear pagina de "Contacto"

### ISSUE THREAD

**Issue by Juanlu1995** [CvQuick/CvQuick#15]
Crear un archivo contacto "contacto.html" que contante un enlace al repositorio del proyecto, una lista de los integrantes del equipo y un formulario de texto para contactar por correo electronico, estilo [https://www.vans.es/ayuda/contacta-con-nosotros.html](url), con campos como nombre, dirección de correo y asunto.
Ésta será la página que aparezca al pulsar "contacto" en el footer #9

**Comment by navarrocantero** [comment]
asignamelo
